### ISSUE TITLE
Save and Restore UX can be interpreted differently

### ISSUE THREAD

**Issue by jakesmolka** [sidharthramesh/medblocks-ui#8]
I just finished your introduction/tutorial blog post and Medblocks UI is looking really cool! Thanks for making it open source.

Everything worked as expected on my side, but I stumbled over one little UX thing:
On Settings -> Customize page the buttons `Save` and `Restore default` appear to be in the context of each element's scope. For instance, if I click on the DV_CODED_TEXT element like in the tutorial all the customization options on the right are changing and moving depending on the type - but so do the `Save` and `Restore default` buttons as well. For me this suggests all changes need to/can be saved or restored individually.

I'm just a backend dev but to illustrate my thoughts here you can see two options where I would have expected a 'global' save and restore button:
![Screenshot from 2021-01-27 09-42-34-edit](https://user-images.githubusercontent.com/30796382/105966367-d88cfc80-6084-11eb-8b26-6f57bd193e1a.png)

**Comment by sidharthramesh** [comment]
@jakesmolka Thank you for the feedback. And yes. You are correct. I will change the UI to signal that these are in fact global save and reset options.
